version: 2
jobs:
  build:
    docker:
      - image: python:3.6-stretch
    steps:
      - checkout
      - run:
         name: Install Dependencies and Run Tests
         command: |
           pip install -r requirements-to-freeze.dev.txt
           make test
